### ISSUE TITLE
コードブロックにハイライト

### ISSUE THREAD

**Issue by k-oketa** [k-oketa/kklab_python_train#1]
@HasegawaTetsuo 
markdown形式のコードブロックではハイライト（色）を付けることができます。
これでより可読性が向上すると思います。

例：
```python
def method:
    return(0)

```
参考サイト
https://dev.classmethod.jp/tool/git/syntax-highlight-language-list/

**Comment by HasegawaTetsuo** [comment]
pyとjavaで指定して変更しました

**Comment by k-oketa** [comment]
対応の方ありがとうございます🙏
