### ISSUE TITLE
ch03を途中まで書きました

### ISSUE THREAD

**Issue by k-oketa** [k-oketa/kklab_python_train#2]
@HasegawaTetsuo 
第三回の資料の初めのほうを途中まで書きました。
この後にDataFrameとPandasの欠損値の説明をしてNumPyとPandasを組み合わせながら簡単に操作してもらうチュートリアルを設ける予定です。最後に演習問題を加えられたら加えます。

今日はもう眠いので中断しますが、ここまででこれも加えてほしい等あれば下にコメントしてもらえると助かります。

ちなみに、現在の進捗はch03ブランチの方に更新してあります。よろしくお願いいたします。

**Comment by HasegawaTetsuo** [comment]
概ね良き…
ほんと助かる…

pandasだと
index:word
data:[100,10,45,50,70,6,2,3,85…]
とか1:200とかもできるからそこを紹介してもいいかもしれない

**Comment by k-oketa** [comment]
@HasegawaTetsuo 
いろいろ書いてみてみました。
これでよければcloseしてください。

**Comment by HasegawaTetsuo** [comment]
あざます…
急にやってもらうことになって申し訳ない。
本当に助かりました。
ありがとうございます。
